[programs.localnet]
metaone = "Metah4NXvuBAFNLHLoie5aiDksKvJsUDRGfXNJRr8EJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dunne/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
